Add seq
SrilekhaKarnala/SequenceGame pull request #1
Opened 2024-07-31 10:45 UTC by SrilekhaKarnala

Created a new Java file named `Sequence.java` and Implemented basic game functionality.

2024-07-31 11:34 UTC, Jinankhan requested changes

2024-07-31 11:34 UTC, Jinankhan commented on Seq.java
> +        int[] a=new int[n];
nit: give better name to the array

2024-07-31 11:34 UTC, Jinankhan commented on Seq.java
> +        int n=sc.nextInt();
make sure the variable names are descriptive

2024-07-31 11:34 UTC, Jinankhan commented on Seq.java
> +        int n=sc.nextInt();
edge case : what if the use enters a character which is not a valid integer?

2024-07-31 11:34 UTC, Jinankhan commented on Seq.java
> +        if(codd==0 || codd%2!=0)
add this logic  in a ternary condition

2024-07-31 11:34 UTC, Jinankhan commented on Seq.java
> +        int codd=0;
descriptive variable names!

2024-07-31 11:34 UTC, Jinankhan commented on Seq.java
> +public class Seq{
Class name should be descriptive too

2024-08-01 07:02 UTC, Jinankhan approved these changes

2024-08-01 07:08 UTC, merged

2024-08-01 07:08 UTC, SrilekhaKarnala commented
Merge Branch1